import Box from "@mui/material/Box";
import Head from "next/head";
import PropTypes from "prop-types";
import React from "react";

const Page = ({ title, description, children, ...rest }) => {
  return (
    <Box {...rest}>
      <Head>
        <title>{"NextJS Mui Scaffold | " + title ?? ""}</title>
        <meta
          name="description"
          content={description ? description : "Generated by create next app"}
        />
        <link rel="icon" href={"/favicon.ico"} />
      </Head>
      {children}
    </Box>
  );
};

export default Page;

Page.propTypes = {
  title: PropTypes.string,
  description: PropTypes.string,
  children: PropTypes.node.isRequired,
};
